var friUserName = document.getElementById("fristUserName");
// console.log(friUserName);
var secUserName = document.getElementById("secondUserName");
// console.log(secUserName);
var lastUserName = document.getElementById("lastUserName");
// console.log(lastUserName);
var uEmail = document.getElementById("userEmail");
// console.log(uEmail);
var uReEmail = document.getElementById("userReEmail");
// console.log(uReEmail);
var uGender = document.getElementById("userGender");
// console.log(uGender);
var uAge = document.getElementById("userAge");
// console.log(uAge);
var uBirthDate = document.getElementById("userBirthDate");
// console.log(uBirthDate);
var uSalary = document.getElementById("userSalary");
// console.log(uSalary);
var uPassword = document.getElementById("userPassword");
// console.log(uPassword);
var uRePassword = document.getElementById("userRePassword");
// console.log(uRePassword);
var registerationBtn = document.getElementById("registerationButton");
// console.log(registerationBtn);
var registerationUserDataCont = document.getElementById("registerationUserDataContainer");
// console.log(registerationUserDataCont);
// registerationBtn.addEventListener("click" , function(){
//     registerationUserDataCont.style.display="block";
// });
function userRegisterationDataNow(){
    var fristUserNameData = document.getElementById("fUserNameData");
    // console.log(fristUserNameData);
    fristUserNameData.innerHTML = `frist user name is : \"${friUserName.value}\"`;
    // console.log(fristUserNameData)
    var secondUserNameData = document.getElementById("sUserNameData");
    // console.log(secondUserNameData);
    secondUserNameData.innerHTML = `second user name is : \"${secUserName.value}\"`;
    // console.log(secondUserNameData);
    var lastUserNameData = document.getElementById("lUserNameData");
    // console.log(lastUserNameData);
    lastUserNameData.innerHTML = `last user name is : \"${lastUserName.value}\"`;
    // console.log(lastUserNameData);
    var userEmailData = document.getElementById("uEmailData");
    // console.log(userEmailData);
    userEmailData.innerHTML = `user email is : \"${uEmail.value}\"`;
    // console.log(userEmailData);
    var userReEmailData = document.getElementById("uReEmailData");
    // console.log(userReEmailData);
    userReEmailData.innerHTML = `user re email is : \"${uReEmail.value}\"`;
    // console.log(userReEmailData);
    var userGenderData = document.getElementById("uGenderData");
    // console.log(userGenderData);
    userGenderData.innerHTML = `user gender is : \"${uGender.value}\"`;
    // console.log(userGenderData);
    var userAgeData = document.getElementById("uAgeData");
    // console.log(userAgeData);
    userAgeData.innerHTML = `user age is : \"${uAge.value} years\"`;
    // console.log(userAgeData);
    var userBirthDateData = document.getElementById("uBirthDateData");
    // console.log(userBirthDateData);
    userBirthDateData.innerHTML = `user birth date is : \"${uBirthDate.value}\"`;
    // console.log(userBirthDateData);
    var userSalaryData = document.getElementById("uSalaryData");
    // console.log(userSalaryData);
    userSalaryData.innerHTML = `user salary is \"${uSalary.value} $\"`;
    // console.log(userSalaryData);
    var userPasswordData = document.getElementById("uPasswordData");
    // console.log(userPasswordData);
    userPasswordData.innerHTML = `user password is : \"${uPassword.value}\"`;
    // console.log(userPasswordData);
    var userRePasswordData = document.getElementById("uRePasswordData");
    // console.log(userRePasswordData);
    userRePasswordData.innerHTML = `user re password is : \"${uRePassword.value}\"`;
    // console.log(userRePasswordData);
};
registerationBtn.addEventListener("click" , function(){
    registerationUserDataCont.style.display= "flex";
    userRegisterationDataNow();
});